services:
  trackyrs-database:
    container_name: trackyrs-database
    image: postgres:${POSTGRES_VERSION}-alpine
    env_file:
      - .env.local
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - trackyrs_network

volumes:
  database_data:

networks:
  trackyrs_network:
    driver: bridge
