FROM node:22.19-alpine

WORKDIR /app

COPY . .

RUN npm install -g bun
RUN bun install

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

CMD ["bunx", "turbo", "run", "start", "--filter=@trackyrs/server"]
